{
 "title": "PredictMaint API - Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request rate por endpoint (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_total[1m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Latencia p95 por endpoint (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, handler) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Tasa de error 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m])) / sum(rate(http_requests_total[1m]))",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "Requests en vuelo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "http_requests_in_progress", "legendFormat": "{{handler}}" }
   ]
  }
 ]
}